name: Build Check on PR

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Download Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Go to folder
        run: cd ./front-app

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
